= Pentester Lab Bootcamp
x3830s

A summary and collection of small programs and scripts created to complete the 15 Pentester Lab Bootcamp exercises.

## Week One
|====
|*Practical Tasks* | *Reading*
a|* [x] Install Linux on a virtualisation system 
* [x] Learn the basics of a scripting language 
a|
* [x] Hypertext Transfer Protocol
* [x] Domain Name System
* [x] Whois
* [x] Network Socket
* [x] Scoping a Pentest
|====
.*Week's Summary:*
This week was fairly straight forward, install a simple, non-infosec related Linux distribution on our chosen virtualization platform. For this I personally chose __*Manjaro*__ as I'm fairly comfortable with an Arch Linux based distribution. I also used VMware workstation Pro to host my guest virtual machine(VM) on my host computer running Windows 10.

 
## Week Two
|====
|*Practical Tasks* | *Reading*
a|
* [x] Install Apache, change home page of the hosted site using vim.
* [x] Change the hostfile to access the Linux system under the name `vulnerable`
* [x] Write an HTTP client to retrieve the homepage using a HTTP library.
* [x] Write an HTTP client to retrieve the homepage of your site using a socket.
* [x] Download BurpSuite view requests and responses.

a|
* [ ] TCP/IP
* [ ] Secure Sockets Layer
* [ ] Keeping notes during a pentest
|====

